package api.novaposta

import com.squareup.moshi.Json

class Datum {

    @Json(name = "Number")
    var number: String? = null
    @Json(name = "Redelivery")
    var redelivery: Int? = null
    @Json(name = "RedeliverySum")
    var redeliverySum: String? = null
    @Json(name = "RedeliveryNum")
    var redeliveryNum: String? = null
    @Json(name = "RedeliveryPayer")
    var redeliveryPayer: String? = null
    @Json(name = "OwnerDocumentType")
    var ownerDocumentType: String? = null
    @Json(name = "LastCreatedOnTheBasisDocumentType")
    var lastCreatedOnTheBasisDocumentType: String? = null
    @Json(name = "LastCreatedOnTheBasisPayerType")
    var lastCreatedOnTheBasisPayerType: String? = null
    @Json(name = "LastCreatedOnTheBasisDateTime")
    var lastCreatedOnTheBasisDateTime: String? = null
    @Json(name = "LastTransactionStatusGM")
    var lastTransactionStatusGM: String? = null
    @Json(name = "LastTransactionDateTimeGM")
    var lastTransactionDateTimeGM: String? = null
    @Json(name = "DateCreated")
    var dateCreated: String? = null
    @Json(name = "CheckWeight")
    var checkWeight: Int? = null
    @Json(name = "SumBeforeCheckWeight")
    var sumBeforeCheckWeight: Int? = null
    @Json(name = "PayerType")
    var payerType: String? = null
    @Json(name = "RecipientFullName")
    var recipientFullName: String? = null
    @Json(name = "RecipientDateTime")
    var recipientDateTime: String? = null
    @Json(name = "ScheduledDeliveryDate")
    var scheduledDeliveryDate: String? = null
    @Json(name = "PaymentMethod")
    var paymentMethod: String? = null
    @Json(name = "CargoDescriptionString")
    var cargoDescriptionString: String? = null
    @Json(name = "CargoType")
    var cargoType: String? = null
    @Json(name = "CitySender")
    var citySender: String? = null
    @Json(name = "CityRecipient")
    var cityRecipient: String? = null
    @Json(name = "WarehouseRecipient")
    var warehouseRecipient: String? = null
    @Json(name = "CounterpartyType")
    var counterpartyType: String? = null
    @Json(name = "AfterpaymentOnGoodsCost")
    var afterpaymentOnGoodsCost: String? = null
    @Json(name = "ServiceType")
    var serviceType: String? = null
    @Json(name = "UndeliveryReasonsSubtypeDescription")
    var undeliveryReasonsSubtypeDescription: String? = null
    @Json(name = "WarehouseRecipientNumber")
    var warehouseRecipientNumber: Int? = null
    @Json(name = "LastCreatedOnTheBasisNumber")
    var lastCreatedOnTheBasisNumber: String? = null
    @Json(name = "WarehouseRecipientInternetAddressRef")
    var warehouseRecipientInternetAddressRef: String? = null
    @Json(name = "MarketplacePartnerToken")
    var marketplacePartnerToken: String? = null
    @Json(name = "ClientBarcode")
    var clientBarcode: String? = null
    @Json(name = "SenderAddress")
    var senderAddress: String? = null
    @Json(name = "RecipientAddress")
    var recipientAddress: String? = null
    @Json(name = "CounterpartySenderDescription")
    var counterpartySenderDescription: String? = null
    @Json(name = "CounterpartyRecipientDescription")
    var counterpartyRecipientDescription: String? = null
    @Json(name = "CounterpartySenderType")
    var counterpartySenderType: String? = null
    @Json(name = "DateScan")
    var dateScan: String? = null
    @Json(name = "PaymentStatus")
    var paymentStatus: String? = null
    @Json(name = "PaymentStatusDate")
    var paymentStatusDate: String? = null
    @Json(name = "AmountToPay")
    var amountToPay: String? = null
    @Json(name = "AmountPaid")
    var amountPaid: String? = null
    @Json(name = "LastAmountTransferGM")
    var lastAmountTransferGM: String? = null
    @Json(name = "LastAmountReceivedCommissionGM")
    var lastAmountReceivedCommissionGM: String? = null
    @Json(name = "DocumentCost")
    var documentCost: Int? = null
    @Json(name = "DocumentWeight")
    var documentWeight: Double? = null
    @Json(name = "AnnouncedPrice")
    var announcedPrice: String? = null
    @Json(name = "RecipientWarehouseTypeRef")
    var recipientWarehouseTypeRef: String? = null
    @Json(name = "RedeliveryPaymentCardRef")
    var redeliveryPaymentCardRef: String? = null
    @Json(name = "RedeliveryPaymentCardDescription")
    var redeliveryPaymentCardDescription: String? = null
    @Json(name = "OwnerDocumentNumber")
    var ownerDocumentNumber: String? = null
    @Json(name = "InternationalDeliveryType")
    var internationalDeliveryType: String? = null
    @Json(name = "Status")
    var status: String? = null
    @Json(name = "StatusCode")
    var statusCode: String? = null
    @Json(name = "RefEW")
    var refEW: String? = null
    @Json(name = "DatePayedKeeping")
    var datePayedKeeping: String? = null

}
